# 工作流名称，不设置的话默认取配置文件名
name: npm-publish

# 触发部署的条件 当 master 分支, 有 push 的操作, 即可触发。
on:
  # 在推或拉请求事件上触发工作流，但仅用于主分支
  push:
    tags:
      - 'v*'
    #branches: # 此处不仅限于监听分支, 还可监听 tag
     # - master
# 一个工作流运行由一个或多个任务组成，这些任务可以顺序地或并行地运行
jobs:
  # 任务名称
  publish-npm:
    # 任务运行的容器类型（虚拟机环境）
    runs-on: ubuntu-latest
    # 任务执行的步骤
    steps:
      - name: Checkout
        # 选择要作为作业中步骤的一部分运行的操作 在这里查：https://github.com/marketplace?type=actions&query=checkout+
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      # npm ERR! 402 Payment Required - PUT https://registry.npmjs.org/@vensst/js-tookit - You must sign up for private packages
      # @xxx/xxxx   npm会认为要发布私包，私包需要收费，需将发布命令改成： npm publish --access public
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
